// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A clothing size recommendation AI agent.
 *
 * - aiSizeRecommendation - A function that handles the size recommendation process.
 * - AiSizeRecommendationInput - The input type for the aiSizeRecommendation function.
 * - AiSizeRecommendationOutput - The return type for the aiSizeRecommendation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiSizeRecommendationInputSchema = z.object({
  height: z.number().describe('Your height in centimeters.'),
  weight: z.number().describe('Your weight in kilograms.'),
  usualFitPreference: z.string().describe('Your usual fit preference (e.g., slim, regular, oversized).'),
  clothingType: z.string().describe('The type of clothing for which you want a size recommendation (e.g., shirt, pants, dress).'),
});
export type AiSizeRecommendationInput = z.infer<typeof AiSizeRecommendationInputSchema>;

const AiSizeRecommendationOutputSchema = z.object({
  sizeRecommendation: z.string().describe('The recommended clothing size.'),
  confidence: z.number().describe('A confidence score (0-1) for the size recommendation.'),
  reasoning: z.string().describe('The reasoning behind the size recommendation.'),
});
export type AiSizeRecommendationOutput = z.infer<typeof AiSizeRecommendationOutputSchema>;

export async function aiSizeRecommendation(input: AiSizeRecommendationInput): Promise<AiSizeRecommendationOutput> {
  return aiSizeRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiSizeRecommendationPrompt',
  input: {schema: AiSizeRecommendationInputSchema},
  output: {schema: AiSizeRecommendationOutputSchema},
  prompt: `You are an AI clothing size recommendation expert. Given the user's height, weight, usual fit preference, and the type of clothing they are looking for, recommend a clothing size.

Height: {{{height}}} cm
Weight: {{{weight}}} kg
Usual Fit Preference: {{{usualFitPreference}}}
Clothing Type: {{{clothingType}}}

Based on this information, provide a size recommendation, a confidence score (0-1) for the recommendation, and the reasoning behind your recommendation.  The size should be a standard size like XS, S, M, L, XL, etc.  If the clothing type is pants, the size should include both waist and inseam measurements.  The confidence score should reflect how sure you are that the user will fit into the recommended size.

Format your response as a JSON object that matches the following schema:
${JSON.stringify(AiSizeRecommendationOutputSchema.describe('The output schema.'))}
`,
});

const aiSizeRecommendationFlow = ai.defineFlow(
  {
    name: 'aiSizeRecommendationFlow',
    inputSchema: AiSizeRecommendationInputSchema,
    outputSchema: AiSizeRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
